{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "1fa538c1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "from jupyter_cadquery import set_defaults, show, Camera, Collapse\n",
    "from build123d import *\n",
    "import asyncio\n",
    "import math\n",
    "from functools import reduce\n",
    "\n",
    "set_defaults(\n",
    "\tviewer=\"Sidecar\",\n",
    "\tedge_accuracy=0.0001,\n",
    "\tticks=25,\n",
    "\tgrid=[True, True, True],\n",
    "\tcad_width=780,\n",
    "\taxes=True,\n",
    "\taxes0=True,\n",
    "\tglass=True,\n",
    "\torbit_control=True,\n",
    "\treset_camera=Camera.CENTER,\n",
    "\tcollapse=Collapse.LEAVES\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "bf8c37db-0315-4b11-af27-de30f61a53df",
   "metadata": {},
   "outputs": [],
   "source": [
    "COLUMN_DIAM = 20\n",
    "BUMP_SIZE = 0.4\n",
    "COLUMN_HEIGHT = 68\n",
    "LIP_THICKNESS = 2\n",
    "\n",
    "NUM_BUMPS = 32\n",
    "BASE_HEIGHT = 15\n",
    "EMBOSS_THICKNESS = 0.2\n",
    "FILLET_RADIUS = 1\n",
    "\n",
    "outer_diam = COLUMN_DIAM + BUMP_SIZE * 2\n",
    "column_radius = COLUMN_DIAM / 2\n",
    "cap_height = outer_diam / 2\n",
    "platform_diff = outer_diam - COLUMN_DIAM\n",
    "base_diam = outer_diam + platform_diff\n",
    "\n",
    "platform_width = outer_diam\n",
    "length = base_diam\n",
    "\n",
    "platform_height = LIP_THICKNESS * 4\n",
    "c_height = COLUMN_HEIGHT - ((BASE_HEIGHT + LIP_THICKNESS) + (cap_height + platform_height))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "f28324ef",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<cad_viewer_widget.widget.CadViewer at 0x201839539b0>"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "async def make_square(length, radius=FILLET_RADIUS):\n",
    "    return RectangleRounded(length, length, radius)\n",
    "\n",
    "async def make_column_profile(column_radius, num_bumps, bump_size):\n",
    "\tside_length = column_radius * math.sin(math.pi / (num_bumps * 2))\n",
    "\n",
    "\tbump_profile = Rot(0,0, -90 - 90 / num_bumps) * Pos(side_length, 0, 0) * EllipticalCenterArc(\n",
    "        (0,0,0),\n",
    "        side_length,\n",
    "        bump_size,\n",
    "        end_angle=180\n",
    "    )\n",
    "\tall_polar_locations = [v for v in PolarLocations(column_radius, count = num_bumps * 2)]\n",
    "\tbump_locations, arc_locations = (\n",
    "        [v for i, v in enumerate(all_polar_locations) if not i % 2],\n",
    "        [v for i, v in enumerate(all_polar_locations) if i % 2]\n",
    "    )\n",
    "\tedges: ShapeList[Edge] = ShapeList([v * bump_profile for v in bump_locations]) + ShapeList([\n",
    "\t\tRadiusArc(\n",
    "            v2.position,\n",
    "            v1.position,\n",
    "            column_radius\n",
    "        ) for v1, v2 in zip(\n",
    "            bump_locations,\n",
    "            arc_locations\n",
    "        )\n",
    "\t])\n",
    "\treturn Rot(0, 0, 90 / num_bumps) * -Face(\n",
    "\t\treduce(\n",
    "\t\t\tlambda x, y: x + y,\n",
    "\t\t\tsorted(\n",
    "                edges,\n",
    "                key=lambda x: x.position_at(0.5).normalized().get_signed_angle(\n",
    "                    Vector(1, 0, 0)\n",
    "                )\n",
    "            )\n",
    "\t\t)\n",
    "\t)\n",
    "\n",
    "async def make_circle(radius, radius2=None):\n",
    "\tif radius2 is not None:\n",
    "\t\treturn Ellipse(radius, radius2)\n",
    "\treturn Circle(radius)\n",
    "\n",
    "\n",
    "async def make_base(\n",
    "\t\tbase_height,\n",
    "\t\tlip_thickness,\n",
    "\t\tcolumn_radius,\n",
    "\t\tbottom_length,\n",
    "\t\tplatform_length,\n",
    "\t\tplinth_height, # default: base_height + lip_thickness\n",
    "\t\tbump_size,\n",
    "\t\tfillet_radius\n",
    "\t):\n",
    "\tr1, r2, r3, plinth_profile = await asyncio.gather(\n",
    "\t\tmake_square(bottom_length, fillet_radius),\n",
    "\t\tmake_square(column_radius * 2, fillet_radius),\n",
    "\t\tmake_square(platform_length, fillet_radius),\n",
    "\t\tmake_circle(column_radius)\n",
    "\t)\n",
    "\n",
    "\tbase_inset = (bottom_length / 2 - column_radius)\n",
    "\n",
    "\treturn loft([\n",
    "\t\tr1,\n",
    "\t\tPlane.XY.offset(lip_thickness) * r1,\n",
    "\t\tPlane.XY.offset(lip_thickness + bump_size) * r2,\n",
    "\t\tPlane.XY.offset(base_height / 2) * r2,\n",
    "\t\tPlane.XY.offset(base_height - (lip_thickness + bump_size * 2)) * r2,\n",
    "\t\tPlane.XY.offset(base_height - lip_thickness) * r3,\n",
    "\t\tPlane.XY.offset(base_height) * r3,\n",
    "\t\tPlane.XY.offset(base_height) * plinth_profile,\n",
    "\t\tPlane.XY.offset(plinth_height) * plinth_profile,\n",
    "\t], ruled=True)\n",
    "\n",
    "async def make_shaft(\n",
    "\t\tshaft_radius,\n",
    "\t\tshaft_height,\n",
    "\t\tplinth_height,\n",
    "\t\tnum_bumps,\n",
    "\t\tbump_size\n",
    "\t):\n",
    "\tprofile, c1, c2 = await asyncio.gather(\n",
    "\t\tmake_column_profile(shaft_radius, num_bumps, bump_size),\n",
    "\t\tmake_circle(shaft_radius),\n",
    "\t\tmake_circle(shaft_radius + bump_size)\n",
    "\t)\n",
    "\tbase = loft([\n",
    "\t\tc2,\n",
    "\t\tPlane.XY.offset(bump_size) * c1\n",
    "\t])\n",
    "\n",
    "\tshaft = extrude(profile, shaft_height) + base + Plane.XY.offset(shaft_height) * Rot(180, 0, 0) * base\n",
    "\treturn Plane.XY.offset(plinth_height) * shaft\n",
    "\n",
    "def make_spiral(num_turns, dist):\n",
    "\tr = lambda theta: (dist / num_turns) * theta / math.pi\n",
    "\tangles = [-x * math.pi / 4 for x in range(num_turns * 8 + 1)]\n",
    "\tpts = [(r(x) * math.cos(x), r(x) * math.sin(x)) for x in angles]\n",
    "\treturn Spline(\n",
    "\t\tpts\n",
    "\t)\n",
    "\n",
    "async def make_cap(platform_length, platform_width, lip_thickness, emboss_thickness):\n",
    "\tplatform_height = lip_thickness * 4\n",
    "\troll = Cylinder(\n",
    "        platform_height / 2,\n",
    "        platform_length,\n",
    "        rotation=(-90, 0, 0),\n",
    "        align=(Align.CENTER, Align.MAX, Align.CENTER)\n",
    "    )\n",
    "\tplatform = Pos(-platform_width / 2, 0, 0) * roll + Pos(platform_width / 2, 0, 0) * roll + Box(\n",
    "        platform_width,\n",
    "        platform_length,\n",
    "        platform_height / 2,\n",
    "        align=(Align.CENTER, Align.CENTER, Align.MIN)\n",
    "    )\n",
    "\tplatform_base = Ellipse(platform_width / 2, platform_length / 2)\n",
    "\tellipcylinder = Pos(0,0,platform_height / 2) * extrude(platform_base, platform_height / 2)\n",
    "\tplatform += ellipcylinder\n",
    "\n",
    "\tspiral = Line(\n",
    "\t\t(0, platform_height / 4),\n",
    "\t\t(platform_width / 2, platform_height / 4)\n",
    "\t) + Pos(\n",
    "        platform_width / 2,\n",
    "        platform_height / 2\n",
    "    ) * Rot(0, 0, 90) * make_spiral(\n",
    "        1,\n",
    "        platform_height / 8\n",
    "    )\n",
    "\tspiral += spiral.mirror(Plane.YZ)\n",
    "\n",
    "\tplatform += Rot(90, 0, 0) * extrude(\n",
    "        -Face(spiral.offset_2d(lip_thickness / 4)),\n",
    "        platform_length / 2 + emboss_thickness,\n",
    "        both=True\n",
    "    )\n",
    "\tc1 = await make_circle(platform_length / 2)\n",
    "\tl = loft([\n",
    "\t\tPlane.XY.offset(platform_height) * platform_base,\n",
    "\t\tPlane.XY.offset(platform_height + lip_thickness) * c1,\n",
    "\t], ruled=True)\n",
    "\n",
    "\treturn platform + l\n",
    "\n",
    "async def make_column():\n",
    "\tcap_step = LIP_THICKNESS #* 1.5\n",
    "\tcap_height = cap_step * 5\n",
    "\tbase, shaft, cap = await asyncio.gather(\n",
    "\t\tmake_base(\n",
    "\t\t\tbase_height=BASE_HEIGHT,\n",
    "\t\t\tlip_thickness=LIP_THICKNESS,\n",
    "\t\t\tcolumn_radius=COLUMN_DIAM / 2,\n",
    "\t\t\tbottom_length=COLUMN_DIAM + BUMP_SIZE * 2,\n",
    "\t\t\tplatform_length=COLUMN_DIAM + BUMP_SIZE * 4,\n",
    "\t\t\tplinth_height=BASE_HEIGHT + LIP_THICKNESS,\n",
    "\t\t\tbump_size=BUMP_SIZE,\n",
    "\t\t\tfillet_radius=FILLET_RADIUS\n",
    "\t\t),\n",
    "\t\tmake_shaft(\n",
    "\t\t\tCOLUMN_DIAM / 2 - BUMP_SIZE,\n",
    "\t\t\tCOLUMN_HEIGHT - ((BASE_HEIGHT + LIP_THICKNESS) + (cap_height)),\n",
    "\t\t\tBASE_HEIGHT + LIP_THICKNESS,\n",
    "\t\t\tNUM_BUMPS,\n",
    "\t\t\tBUMP_SIZE\n",
    "\t\t),\n",
    "\t\tmake_cap(\n",
    "\t\t\tCOLUMN_DIAM,\n",
    "\t\t\tCOLUMN_DIAM + BUMP_SIZE,\n",
    "\t\t\tcap_step,\n",
    "\t\t\tEMBOSS_THICKNESS,\n",
    "\t\t)\n",
    "\t)\n",
    "\t\n",
    "\treturn reduce(lambda x, y: x + y, [\n",
    "        base,\n",
    "        shaft,\n",
    "        (Plane.XY.offset(COLUMN_HEIGHT) * Rot(180, 0, 0) * cap)\n",
    "    ])\n",
    "\t# return [base, shaft, (Plane.XY.offset(COLUMN_HEIGHT) * Rot(180, 0, 0) * cap)]\n",
    "\t# return base\n",
    "\n",
    "column = await make_column()\n",
    "show(column)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0b67ad91-4d50-4d47-ad6a-72ae1caf2b94",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
