{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1fa538c1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting auto display for build123d BuildPart, BuildSketch, BuildLine, ShapeList\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "from jupyter_cadquery import set_defaults, show, Camera, Collapse\n",
    "import math\n",
    "from build123d import *\n",
    "\n",
    "set_defaults(\n",
    "\tviewer=\"Sidecar\",\n",
    "\tedge_accuracy=0.0001,\n",
    "\tticks=25,\n",
    "\tgrid=[True, True, True],\n",
    "\tcad_width=780,\n",
    "\taxes=True,\n",
    "\taxes0=True,\n",
    "\tglass=True,\n",
    "\torbit_control=True,\n",
    "\treset_camera=Camera.CENTER,\n",
    "\tcollapse=Collapse.LEAVES\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f28324ef",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "TABLET_THICKNESS = 5\n",
    "CLAMP_THICKNESS = 1\n",
    "CLAMP_WIDTH  = 40\n",
    "\n",
    "RAIL_WIDTH = 30\n",
    "RAIL_HEIGHT = 6\n",
    "TABLET_WIDTH = 140\n",
    "THUMB_SCREW_DIAM = 30\n",
    "WASHER_THICKNESS = 0.5\n",
    "\n",
    "MARGIN = 0.2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "70cd5fa0-5eca-49aa-8045-48307715f8b2",
   "metadata": {},
   "outputs": [],
   "source": [
    "SCREW_SHAFT_DIAM = 5\n",
    "SCREW_HEAD_DIAM = 8.6\n",
    "SCREW_HEAD_LENGTH = 5\n",
    "SCREW_SHAFT_LENGTH = 25\n",
    "HEX_NUT_THICKNESS = SCREW_HEAD_LENGTH / 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "538d7b12-1aa1-410b-aa2f-39ed884723be",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "cc++\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<cad_viewer_widget.widget.CadViewer at 0x18cf476e2a0>"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "STEP = RAIL_HEIGHT / 2\n",
    "\n",
    "def make_rail_profile(width_step, height_step):\n",
    "    return Polyline(\n",
    "        (width_step, 0),\n",
    "        (width_step + height_step, height_step),\n",
    "        (width_step, height_step * 2),\n",
    "        (-width_step, height_step * 2),\n",
    "        (-(width_step + height_step), height_step),\n",
    "        (-width_step, 0)\n",
    "    ).close()\n",
    "\n",
    "def make_rider_profile(width_step, height_step, margin=MARGIN):\n",
    "    return Polyline(\n",
    "        (-(width_step + margin), height_step * 2),\n",
    "        (-(width_step + height_step + margin), height_step),\n",
    "        (-(width_step + margin), 0),\n",
    "        (width_step + margin, 0),\n",
    "        (width_step + height_step + margin, height_step),\n",
    "        (width_step + margin, height_step * 2),\n",
    "        (width_step + margin + height_step * 2, height_step * 2),\n",
    "        (width_step + margin + height_step * 2, 0),\n",
    "        (width_step + margin + height_step * 2, -height_step),\n",
    "        (-(width_step + margin + height_step * 2), -height_step),\n",
    "        (-(width_step + margin + height_step * 2), height_step * 2),\n",
    "    ).close()\n",
    "\n",
    "def make_rail(\n",
    "    rail_width,\n",
    "    rail_height,\n",
    "    rail_length,\n",
    "    thumb_screw_radius,\n",
    "    screw_head_radius,\n",
    "    screw_shaft_radius,\n",
    "    hex_nut_thickness\n",
    "):\n",
    "    profile = make_rail_profile(rail_width / 2, rail_height / 2)\n",
    "    rail = Plane.XZ * extrude(Face(profile), rail_length)\n",
    "\n",
    "    rail -= Plane(\n",
    "        rail.faces().filter_by(Axis.Z).sort_by(Axis.Z).first\n",
    "    ) * Pos(\n",
    "        0,\n",
    "        rail_length / 2 - thumb_screw_radius\n",
    "    ) * Hole(\n",
    "        screw_shaft_radius,\n",
    "        rail_height\n",
    "    )\n",
    "\n",
    "    rail -= Plane(\n",
    "        rail.faces().filter_by(Axis.Z).sort_by(Axis.Z).last\n",
    "    ) * Pos(\n",
    "        0,\n",
    "        rail_length / 2 - thumb_screw_radius\n",
    "    ) * extrude(\n",
    "        RegularPolygon(screw_head_radius, 6),\n",
    "        -hex_nut_thickness\n",
    "    )\n",
    "    # get screw_position/plane from rail\n",
    "    return rail\n",
    "\n",
    "def make_rider(\n",
    "    rail_width,\n",
    "    rail_height,\n",
    "    rail_length,\n",
    "    thumb_screw_radius,\n",
    "    screw_shaft_radius\n",
    "):\n",
    "    profile = make_rider_profile(rail_width / 2, rail_height / 2)\n",
    "    rider = Plane.XZ * extrude(-Face(profile), rail_length)\n",
    "\n",
    "    p = Plane(\n",
    "        rider.faces().filter_by(Axis.Z).sort_by(Axis.Z).first\n",
    "    )\n",
    "    rider = rider - extrude(\n",
    "        p * SlotCenterPoint(\n",
    "            (0,0),\n",
    "            (0, rail_length - thumb_screw_radius),\n",
    "            screw_shaft_radius\n",
    "        ),\n",
    "        rail_height\n",
    "    )\n",
    "    return rider\n",
    "\n",
    "def make_thumbscrew(\n",
    "    thumb_screw_radius,\n",
    "    screw_shaft_radius,\n",
    "    screw_shaft_length,\n",
    "    screw_head_radius,\n",
    "    screw_head_length,\n",
    "    rider_height,\n",
    "    washer_thickness\n",
    "):\n",
    "    thumbscrew = Cylinder(\n",
    "        thumb_screw_radius,\n",
    "        screw_shaft_length + screw_head_length - rider_height - washer_thickness,\n",
    "        align=(Align.CENTER, Align.CENTER, Align.MIN)\n",
    "    )\n",
    "    thumbscrew -= Plane(\n",
    "        thumbscrew.faces().filter_by(Axis.Z).first\n",
    "    ) * CounterBoreHole(\n",
    "        screw_shaft_radius,\n",
    "        screw_head_radius,\n",
    "        screw_head_length,\n",
    "        screw_shaft_length\n",
    "    )\n",
    "    return thumbscrew\n",
    "\n",
    "thumbscrew = make_thumbscrew(\n",
    "    THUMB_SCREW_DIAM / 2,\n",
    "    SCREW_SHAFT_DIAM / 2,\n",
    "    SCREW_SHAFT_LENGTH,\n",
    "    SCREW_HEAD_DIAM / 2,\n",
    "    SCREW_HEAD_LENGTH,\n",
    "    STEP * 3,\n",
    "    WASHER_THICKNESS\n",
    ")\n",
    "rail, rider = make_rail(\n",
    "    RAIL_WIDTH,\n",
    "    RAIL_HEIGHT,\n",
    "    TABLET_WIDTH / 2,\n",
    "    THUMB_SCREW_DIAM / 2,\n",
    "    SCREW_HEAD_DIAM / 2,\n",
    "    SCREW_SHAFT_DIAM / 2,\n",
    "    SCREW_HEAD_LENGTH / 2\n",
    "), make_rider(\n",
    "    RAIL_WIDTH,\n",
    "    RAIL_HEIGHT,\n",
    "    TABLET_WIDTH / 2,\n",
    "    THUMB_SCREW_DIAM / 2,\n",
    "    SCREW_SHAFT_DIAM / 2\n",
    ")\n",
    "bolt = make_bolt(\n",
    "    SCREW_SHAFT_DIAM / 2,\n",
    "    SCREW_SHAFT_LENGTH,\n",
    "    SCREW_HEAD_DIAM / 2,\n",
    "    SCREW_HEAD_LENGTH\n",
    ")\n",
    "\n",
    "p = Plane(rider.faces().filter_by(Axis.Z).sort_by(Axis.Z).first)\n",
    "pos = p * Pos(0, -TABLET_WIDTH / 4 + THUMB_SCREW_DIAM / 2, WASHER_THICKNESS)\n",
    "\n",
    "show(\n",
    "    rail,\n",
    "    rider,\n",
    "    pos * thumbscrew,\n",
    "    Plane(\n",
    "        pos * thumbscrew.faces().filter_by(Axis.Z).first\n",
    "    ).offset(-5) * bolt, colors=[\n",
    "        (232, 176, 36),\n",
    "        (232, 176, 36),\n",
    "        (232, 176, 36),\n",
    "        (150, 150, 150)\n",
    "    ]\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a48ea362-b8c1-460a-8036-76648e7ac088",
   "metadata": {},
   "outputs": [],
   "source": [
    "class BoltBlank(BasePartObject):\n",
    "    def __init__(self, shaft_radius, shaft_length, head_radius, head_length, rotation=(), mode=mode.ADD):\n",
    "        super().__init(self, part, rotation, mode)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
