[project]
name = "components"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aneeshnazar", email = "aneeshnazar@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "build123d>=0.9.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
